### ISSUE TITLE
Multiple builderrors after updating version 3.11.0 to 3.12.0

### ISSUE THREAD

**Issue by Wizzel1** [googleapis/nodejs-secret-manager#363]
Thanks for stopping by to ask us a question! Please make sure to include:
- What you're trying to do
I was trying to install the latest package version : 3.12.0.  And run  `npm tsc`
- What I have tried
I tried to delete the node_modules folder and reinstall my dependencies, but that didn't work

This is the build error : 
```
node_modules/@google-cloud/common/build/src/service.d.ts:29:18 - error TS2430: Interface 'ServiceOptions' incorrectly extends interface 'GoogleAuthOptions<JSONClient>'.
  Types of property 'authClient' are incompatible.
    Type 'GoogleAuth<JSONClient>' is not assignable to type 'JSONClient'.

29 export interface ServiceOptions extends GoogleAuthOptions {
                    ~~~~~~~~~~~~~~

node_modules/@google-cloud/common/build/src/util.d.ts:42:18 - error TS2430: Interface 'MakeAuthenticatedRequestFactoryConfig' incorrectly extends interface 'GoogleAuthOptions<JSONClient>'.
  Types of property 'authClient' are incompatible.
    Type 'GoogleAuth<JSONClient>' is not assignable to type 'JSONClient'.
      Type 'GoogleAuth<JSONClient>' is missing the following properties from type 'JWT': createScoped, getRequestMetadataAsync, fetchIdToken, hasUserScopes, and 53 more.

42 export interface MakeAuthenticatedRequestFactoryConfig extends GoogleAuthOptions {

```

**Comment by bcoe** [comment]
@Wizzel1 if you delete your `package-lock.json` and `node_modules`, I believe a fresh install of the library should work for you. Sorry for the inconvenience.

Please let us know if you continue running into any issues.
